### ISSUE TITLE
Unable to find the resource: /META-INF/BenchmarkList

### ISSUE THREAD

**Issue by liufengyun** [liufengyun/bench#3]
On some new machines, we encounter the exception:

```
fliu@lamppc34:/localhome/fliu/bench$ target/pack/bin/bench tests/implicit_cache.scala
Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to find the resource: /META-INF/BenchmarkList
	at org.openjdk.jmh.runner.AbstractResourceReader.getReaders(AbstractResourceReader.java:98)
	at org.openjdk.jmh.runner.BenchmarkList.find(BenchmarkList.java:122)
	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:256)
	at org.openjdk.jmh.runner.Runner.run(Runner.java:206)
	at dotty.tools.benchmarks.Bench$.main(Benchmarks.scala:37)
	at dotty.tools.benchmarks.Bench.main(Benchmarks.scala)
```

**Comment by liufengyun** [comment]
First, you need to run `sbt jmh:compile` before packing.
