### ISSUE TITLE
benchmark status

### ISSUE THREAD

**Issue by liufengyun** [liufengyun/bench#4]

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark finished success Wed Jul 26 12:10:32 CEST 2017

**Comment by liufengyun** [comment]
benchmark finished success Wed Jul 26 14:00:40 CEST 2017

**Comment by liufengyun** [comment]
benchmark finished success Wed Jul 26 15:25:43 CEST 2017

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
benchmark failed

**Comment by liufengyun** [comment]
[bot]benchmark failed

**Comment by liufengyun** [comment]
[bot]benchmark failed

**Comment by liufengyun** [comment]
test

**Comment by liufengyun** [comment]
[bot]benchmark failed

**Comment by liufengyun** [comment]
[bot]benchmark finished success Tue Aug  1 01:01:59 CEST 2017

**Comment by liufengyun** [comment]
[bot]benchmark failed

**Comment by liufengyun** [comment]
[bot]benchmark finished success Wed Aug  2 01:10:22 CEST 2017

**Comment by liufengyun** [comment]
[bot]benchmark failed

**Comment by liufengyun** [comment]
[bot] regression for following benchmarks:

measure "tests/exhaustivity-V.scala" $PROG_HOME/tests/exhaustivity-V.scala

Error message:

[31m12 |[0m    [33mcase[0m ([36m_,[0m [35mB[0m, _, _, _, [35mB[0m, _, _, _, [35mA[0m, [35mA[0m, [35mA[0m, _, _, _) [35m=>[0m [31m3[0m
[31m13 |[0m    [33mcase[0m ([36m_,[0m _, [35mB[0m, _, _, _, [35mB[0m, _, _, [35mB[0m, _, _, [35mA[0m, [35mA[0m, _) [35m=>[0m [31m4[0m
[31m14 |[0m    [33mcase[0m ([36m_,[0m _, _, [35mB[0m, _, _, _, [35mB[0m, _, _, [35mB[0m, _, [35mB[0m, _, [35mA[0m) [35m=>[0m [31m5[0m
[31m15 |[0m    [33mcase[0m ([36m_,[0m _, _, _, [35mB[0m, _, _, _, [35mB[0m, _, _, [35mB[0m, _, [35mB[0m, [35mB[0m) [35m=>[0m [31m6[0m
[31m16 |[0m  }

one warning found
2140.498 ms/op


Result "dotty.tools.benchmarks.Worker.compile":
  2161.970 ?(99.9%) 28.335 ms/op [Average]
  (min, avg, max) = (2117.317, 2161.970, 2221.749), stdev = 32.631
  CI (99.9%): [2133.634, 2190.305] (assumes normal distribution)


# Run complete. Total time: 00:01:12

Benchmark       Mode  Cnt     Score    Error  Units
Worker.compile  avgt   20  2161.970 ? 28.335  ms/op


[check  for more information]

**Comment by liufengyun** [comment]
[bot]benchmark finished success Thu Aug  3 01:48:25 CEST 2017

**Comment by liufengyun** [comment]
[bot]benchmark failed

**Comment by liufengyun** [comment]
[bot] regression for following benchmarks:

measure "tests/implicitNums.scala" $PROG_HOME/tests/implicitNums.scala

Error message:

	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[0m[[31merror[0m] [0m(dotty-interfaces/*:[31mivySbt[0m) Could not create file /data/workspace/bench/dotty/interfaces/target/streams/$global/ivySbt/$global/streams/outjava.io.IOException: No such file or directory[0m
[0m[[31merror[0m] [0mTotal time: 0 s, completed Aug 3, 2017 1:51:35 PM[0m
@liufengyun commented 0 seconds ago:
    [bot]benchmark failed


Commented.


[check logs/08-03-12.06-regression.out for more information]

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

measure "tests/implicitNums.scala" tests/implicitNums.scala

**Comment by liufengyun** [comment]
[bot]benchmark finished success Fri Aug  4 00:17:25 CEST 2017

**Comment by liufengyun** [comment]
[bot] regression for following benchmarks:

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

Error message:

To git@github.com:liufengyun/bench.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:liufengyun/bench.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


[check logs/08-04-13.32-regression.out for more information]

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2353 -t 2384

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2384 -t 2389

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2509 -t 2538

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2547 -t 2523

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot] regression failed for following benchmarks:

arguments: -f 2523 -t 2587

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

Error message:

	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[0m[[31merror[0m] [0m(dotty-compiler/*:[31mprojectDescriptors[0m) Could not create file /data/workspace/bench/dotty/compiler/target/streams/$global/projectDescriptors/$global/streams/outjava.io.IOException: No such file or directory[0m
[0m[[31merror[0m] [0mTotal time: 0 s, completed Aug 4, 2017 9:22:30 PM[0m


[check logs/08-04-21.15-regression.out for more information]

**Comment by liufengyun** [comment]
[bot]benchmark finished success Sat Aug  5 00:07:31 CEST 2017

**Comment by liufengyun** [comment]
[bot]benchmark finished success Sat Aug  5 01:04:14 CEST 2017

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2523 -t 2587

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2587 -t 2606

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2606 -t 2619

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2619 -t 2643

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2674 -t 2694

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2694 -t 2719

measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)

**Comment by liufengyun** [comment]
[bot]benchmark finished success Sun Aug  6 00:49:56 CEST 2017

**Comment by liufengyun** [comment]
[bot] cron failed

On branch master
Changes not staged for commit:
	modified:   build.sbt
	modified:   dotty (new commits, untracked content)
	modified:   projects/dotty (modified content, untracked content)
	modified:   web (new commits)

Untracked files:
	bin/stdlib
	bin/stdlib-plan
	logs/
	output.txt
	site/

no changes added to commit

[check logs/08-07.out for more information]

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2406 -s 10

measure "dotty" $(find $PROG_HOME/dotty/compiler/src/dotty -name *.scala -o -name *.java)

**Comment by liufengyun** [comment]
[bot] cron failed

On branch master
Changes not staged for commit:
	modified:   bin/charts.js
	modified:   build.sbt
	modified:   dotty (new commits, untracked content)
	modified:   projects/dotty (modified content, untracked content)
	modified:   web (new commits)

Untracked files:
	logs/
	output.txt
	site/

no changes added to commit

[check logs/08-08.out for more information]

**Comment by liufengyun** [comment]
[bot] regression failed for following benchmarks:

arguments: -f 1636 -t 2406 -s 10

measure "dotty" $(find dotty/compiler/src/dotty -name *.scala -o -name *.java)
measure "tests/scala-library" -language:Scala2 $(find tests/scala-library -name *.scala)
measure "tests/implicit_cache.scala" tests/implicit_cache.scala
measure "tests/implicit-scope-loop.scala" tests/implicit-scope-loop.scala
measure "tests/i1535.scala" tests/i1535.scala
measure "tests/i1687.scala" tests/i1687.scala
measure "tests/Vector.scala" tests/Vector.scala
measure "tests/empty-class.scala" tests/empty-class.scala
measure "tests/empty-object.scala" tests/empty-object.scala
measure "tests/empty-file.scala" tests/empty-file.scala
measure "tests/patmatexhaust.scala" tests/patmatexhaust.scala
measure "tests/exhaustivity-I.scala" tests/exhaustivity-I.scala
measure "tests/exhaustivity-S.scala" tests/exhaustivity-S.scala
measure "tests/exhaustivity-T.scala" tests/exhaustivity-T.scala
measure "tests/exhaustivity-V.scala" tests/exhaustivity-V.scala
measure "tests/implicitNums.scala" tests/implicitNums.scala

Error message:

On branch master
Changes not staged for commit:
	modified:   build.sbt
	modified:   dotty (new commits, untracked content)
	modified:   web (new commits)

Untracked files:
	logs/
	output.txt
	site/

no changes added to commit


[check logs/08-08-00.45-regression.out for more information]

**Comment by liufengyun** [comment]
[bot] regression failed for following benchmarks:

arguments: -f 1636 -t 2406 -s 10

measure "dotty" $(find dotty/compiler/src/dotty -name *.scala -o -name *.java)

Error message:

On branch master
Changes not staged for commit:
	modified:   bin/plan
	modified:   build.sbt
	modified:   dotty (new commits, untracked content)
	modified:   web (new commits)

Untracked files:
	logs/
	output.txt
	site/

no changes added to commit


[check logs/08-08-00.56-regression.out for more information]

**Comment by liufengyun** [comment]
[bot] regression failed for following benchmarks:

arguments: -f 1733 -t 2406 -s 10

measure "dotty" $(find dotty/compiler/src/dotty -name *.scala -o -name *.java)

Error message:

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)




# Run complete. Total time: 00:00:28

Benchmark  Mode  Cnt  Score   Error  Units
datamash: invalid input: field 1 requested, line 1 has only 0 fields


[check logs/08-08-01.08-regression.out for more information]

**Comment by liufengyun** [comment]
[bot] regression failed for following benchmarks:

arguments: -f 2022 -t 2406 -s 10

measure "dotty" $(find dotty/compiler/src/dotty -name *.scala -o -name *.java)

Error message:

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)




# Run complete. Total time: 00:00:31

Benchmark  Mode  Cnt  Score   Error  Units
datamash: invalid input: field 1 requested, line 1 has only 0 fields


[check logs/08-08-01.17-regression.out for more information]

**Comment by liufengyun** [comment]
[bot] cron failed

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)




# Run complete. Total time: 00:00:08

Benchmark  Mode  Cnt  Score   Error  Units
datamash: invalid input: field 1 requested, line 1 has only 0 fields

[check logs/08-09.out for more information]

**Comment by liufengyun** [comment]
[bot]benchmark finished success Wed Aug  9 10:12:23 CEST 2017

**Comment by liufengyun** [comment]
[bot] regression finished successfully:

arguments: -f 2956

measure "dotty" $(find dotty/compiler/src/dotty -name *.scala -o -name *.java)

**Comment by liufengyun** [comment]
[bot] cron failed

On branch master
Changes not staged for commit:
	modified:   dotty (new commits, untracked content)
	modified:   web (new commits)

Untracked files:
	logs/
	site/

no changes added to commit

[check logs/08-10.out for more information]

**Comment by liufengyun** [comment]
[bot]benchmark finished success Fri Aug 11 00:38:42 CEST 2017

Visit https://liufengyun.github.io/bench/ to see the changes.

**Comment by liufengyun** [comment]
[bot] cron failed

On branch master
Changes not staged for commit:
	modified:   dotty (new commits, untracked content)
	modified:   web (new commits)

Untracked files:
	logs/
	output.txt
	site/

no changes added to commit

[check logs/08-12.out for more information]

**Comment by liufengyun** [comment]
[bot] cron failed

On branch master
Changes not staged for commit:
	modified:   dotty (new commits, untracked content)
	modified:   web (new commits)

Untracked files:
	logs/
	output.txt
	site/

no changes added to commit

[check logs/08-13.out for more information]

**Comment by liufengyun** [comment]
[bot] cron failed

On branch master
Changes not staged for commit:
	modified:   dotty (new commits, untracked content)
	modified:   web (new commits)

Untracked files:
	logs/
	output.txt
	site/

no changes added to commit

[check logs/08-14.out for more information]

**Comment by liufengyun** [comment]
[bot] cron failed

On branch master
Changes not staged for commit:
	modified:   dotty (new commits, untracked content)
	modified:   web (new commits)

Untracked files:
	logs/
	output.txt
	site/

no changes added to commit

[check logs/08-15.out for more information]

**Comment by liufengyun** [comment]
[bot]benchmark finished success Wed Aug 16 00:38:14 CEST 2017

Visit https://liufengyun.github.io/bench/ to see the changes.

**Comment by liufengyun** [comment]
[bot]benchmark finished success Thu Aug 17 03:08:12 CEST 2017

Visit https://liufengyun.github.io/bench/ to see the changes.

**Comment by liufengyun** [comment]
test

**Comment by liufengyun** [comment]
test
